package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestSmbApply_GeneratesFile(t *testing.T) {
	dir := t.TempDir()
	cfgPath := filepath.Join(dir, "config.yaml")
	outPath := filepath.Join(dir, "smb-overrides.conf")

	cfg := `smb:
  overrides:
    - share: "Media"
      directives:
        guest ok: "yes"`
	if err := os.WriteFile(cfgPath, []byte(cfg), 0644); err != nil {
		t.Fatalf("failed to write config: %v", err)
	}

	result := runSmbApplyWithPaths(nil, cfgPath, outPath)
	if result != 0 {
		t.Fatalf("expected exit 0, got %d", result)
	}

	if _, err := os.Stat(outPath); err != nil {
		t.Fatalf("expected output file to exist: %v", err)
	}

	content, err := os.ReadFile(outPath)
	if err != nil {
		t.Fatalf("failed to read output file: %v", err)
	}
	if !strings.Contains(string(content), "[Media]") {
		t.Errorf("expected [Media] in output, got:\n%s", content)
	}
}

func TestSmbApply_EmptyOverrides(t *testing.T) {
	dir := t.TempDir()
	cfgPath := filepath.Join(dir, "config.yaml")
	outPath := filepath.Join(dir, "smb-overrides.conf")

	cfg := `smb:
  overrides: []`
	if err := os.WriteFile(cfgPath, []byte(cfg), 0644); err != nil {
		t.Fatalf("failed to write config: %v", err)
	}

	result := runSmbApplyWithPaths(nil, cfgPath, outPath)
	if result != 0 {
		t.Fatalf("expected exit 0 for empty overrides, got %d", result)
	}

	content, err := os.ReadFile(outPath)
	if err != nil {
		t.Fatalf("expected output file to exist: %v", err)
	}
	if !strings.Contains(string(content), "# Generated by unas-custom") {
		t.Errorf("expected header comment in output, got:\n%s", content)
	}
}

func TestSmbApply_MissingConfig(t *testing.T) {
	dir := t.TempDir()
	outPath := filepath.Join(dir, "smb-overrides.conf")

	result := runSmbApplyWithPaths(nil, filepath.Join(dir, "nonexistent.yaml"), outPath)
	if result != 1 {
		t.Fatalf("expected exit 1 for missing config, got %d", result)
	}
}

func TestSmbApply_InvalidConfig(t *testing.T) {
	dir := t.TempDir()
	cfgPath := filepath.Join(dir, "config.yaml")
	outPath := filepath.Join(dir, "smb-overrides.conf")

	if err := os.WriteFile(cfgPath, []byte("{unclosed: [bracket"), 0644); err != nil {
		t.Fatalf("failed to write config: %v", err)
	}

	result := runSmbApplyWithPaths(nil, cfgPath, outPath)
	if result != 1 {
		t.Fatalf("expected exit 1 for invalid config, got %d", result)
	}
}

func TestSmbApply_CreatesDirectory(t *testing.T) {
	dir := t.TempDir()
	cfgPath := filepath.Join(dir, "config.yaml")
	// Nested path that doesn't exist yet
	outPath := filepath.Join(dir, "nested", "subdir", "smb-overrides.conf")
	cfg := `smb:
  overrides: []`
	if err := os.WriteFile(cfgPath, []byte(cfg), 0644); err != nil {
		t.Fatalf("failed to write config: %v", err)
	}

	result := runSmbApplyWithPaths(nil, cfgPath, outPath)
	if result != 0 {
		t.Fatalf("expected exit 0 when creating nested directories, got %d", result)
	}

	if _, err := os.Stat(outPath); err != nil {
		t.Errorf("expected file to be created at %s: %v", outPath, err)
	}
}

func TestSmbApply_FileContent(t *testing.T) {
	dir := t.TempDir()
	cfgPath := filepath.Join(dir, "config.yaml")
	outPath := filepath.Join(dir, "smb-overrides.conf")

	cfg := `smb:
  overrides:
    - share: "Documents"
      directives:
        read only: "no"
        valid users: "@wheel"`
	if err := os.WriteFile(cfgPath, []byte(cfg), 0644); err != nil {
		t.Fatalf("failed to write config: %v", err)
	}

	result := runSmbApplyWithPaths(nil, cfgPath, outPath)
	if result != 0 {
		t.Fatalf("expected exit 0, got %d", result)
	}

	content, err := os.ReadFile(outPath)
	if err != nil {
		t.Fatalf("failed to read output file: %v", err)
	}
	s := string(content)

	if !strings.Contains(s, "[Documents]") {
		t.Errorf("expected [Documents] section in output, got:\n%s", s)
	}
	if !strings.Contains(s, "read only = no") {
		t.Errorf("expected 'read only = no' directive in output, got:\n%s", s)
	}
	if !strings.Contains(s, "valid users = @wheel") {
		t.Errorf("expected 'valid users = @wheel' directive in output, got:\n%s", s)
	}
	if !strings.Contains(s, "# Generated by unas-custom") {
		t.Errorf("expected header comment in output, got:\n%s", s)
	}
}

func TestSmbApply_MultipleShares(t *testing.T) {
	dir := t.TempDir()
	cfgPath := filepath.Join(dir, "config.yaml")
	outPath := filepath.Join(dir, "smb-overrides.conf")

	cfg := `smb:
  overrides:
    - share: "Photos"
      directives:
        guest ok: "yes"
    - share: "Backup"
      directives:
        read only: "yes"
        valid users: "admin"`
	if err := os.WriteFile(cfgPath, []byte(cfg), 0644); err != nil {
		t.Fatalf("failed to write config: %v", err)
	}

	result := runSmbApplyWithPaths(nil, cfgPath, outPath)
	if result != 0 {
		t.Fatalf("expected exit 0, got %d", result)
	}

	content, err := os.ReadFile(outPath)
	if err != nil {
		t.Fatalf("failed to read output file: %v", err)
	}
	s := string(content)

	if !strings.Contains(s, "[Photos]") {
		t.Errorf("expected [Photos] section in output, got:\n%s", s)
	}
	if !strings.Contains(s, "[Backup]") {
		t.Errorf("expected [Backup] section in output, got:\n%s", s)
	}
}
