package smb

import (
	"fmt"
	"sort"
	"strings"

	"github.com/bbettridge/unas-custom/internal/config"
)

// GenerateOverrides produces a valid Samba INI configuration string from SMBOverride structs.
// Output format:
//
//	# Generated by unas-custom — do not edit manually
//	[ShareName]
//	  key = value
//
// Returns error if any override has empty Share name or empty directive key.
func GenerateOverrides(overrides []config.SMBOverride) (string, error) {
	// Validate all overrides first
	for i, override := range overrides {
		if override.Share == "" {
			return "", fmt.Errorf("override %d: share name cannot be empty", i)
		}
		for key := range override.Directives {
			if key == "" {
				return "", fmt.Errorf("override %d: directive key cannot be empty", i)
			}
		}
	}

	var buf strings.Builder

	// Write header comment
	buf.WriteString("# Generated by unas-custom — do not edit manually\n")

	// If no overrides, return header only
	if len(overrides) == 0 {
		return buf.String(), nil
	}

	// Write each share section
	for _, override := range overrides {
		buf.WriteString("\n[")
		buf.WriteString(override.Share)
		buf.WriteString("]\n")

		// Sort directive keys for consistent output
		keys := make([]string, 0, len(override.Directives))
		for key := range override.Directives {
			keys = append(keys, key)
		}
		sort.Strings(keys)

		// Write directives with 2-space indent
		for _, key := range keys {
			buf.WriteString("  ")
			buf.WriteString(key)
			buf.WriteString(" = ")
			buf.WriteString(override.Directives[key])
			buf.WriteString("\n")
		}
	}

	return buf.String(), nil
}
