package smb

import (
	"strings"
	"testing"

	"github.com/bbettridge/unas-custom/internal/config"
)

func TestGenerateOverrides_SingleShare(t *testing.T) {
	overrides := []config.SMBOverride{
		{
			Share: "Media",
			Directives: map[string]string{
				"write list": "media,admin",
			},
		},
	}

	result, err := GenerateOverrides(overrides)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	// Should contain header
	if !strings.Contains(result, "# Generated by unas-custom — do not edit manually") {
		t.Error("missing header comment")
	}

	// Should contain share section
	if !strings.Contains(result, "[Media]") {
		t.Error("missing share section [Media]")
	}

	// Should contain directive with 2-space indent
	if !strings.Contains(result, "  write list = media,admin") {
		t.Error("missing or incorrectly formatted directive")
	}
}

func TestGenerateOverrides_MultipleShares(t *testing.T) {
	overrides := []config.SMBOverride{
		{
			Share: "Media",
			Directives: map[string]string{
				"write list": "media,admin",
			},
		},
		{
			Share: "Backup",
			Directives: map[string]string{
				"guest ok": "no",
			},
		},
	}

	result, err := GenerateOverrides(overrides)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	// Should contain both share sections
	if !strings.Contains(result, "[Media]") {
		t.Error("missing share section [Media]")
	}
	if !strings.Contains(result, "[Backup]") {
		t.Error("missing share section [Backup]")
	}

	// Should contain both directives
	if !strings.Contains(result, "write list = media,admin") {
		t.Error("missing Media directive")
	}
	if !strings.Contains(result, "guest ok = no") {
		t.Error("missing Backup directive")
	}
}

func TestGenerateOverrides_MultipleDirectives(t *testing.T) {
	overrides := []config.SMBOverride{
		{
			Share: "Media",
			Directives: map[string]string{
				"write list":         "media,admin",
				"guest ok":           "no",
				"fruit:time machine": "yes",
			},
		},
	}

	result, err := GenerateOverrides(overrides)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	// Should contain all directives
	if !strings.Contains(result, "write list = media,admin") {
		t.Error("missing write list directive")
	}
	if !strings.Contains(result, "guest ok = no") {
		t.Error("missing guest ok directive")
	}
	if !strings.Contains(result, "fruit:time machine = yes") {
		t.Error("missing fruit:time machine directive")
	}
}

func TestGenerateOverrides_EmptyOverrides(t *testing.T) {
	overrides := []config.SMBOverride{}

	result, err := GenerateOverrides(overrides)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	// Should contain header comment only
	if !strings.Contains(result, "# Generated by unas-custom — do not edit manually") {
		t.Error("missing header comment")
	}

	// Should not contain any share sections
	if strings.Contains(result, "[") {
		t.Error("should not contain share sections for empty overrides")
	}
}

func TestGenerateOverrides_SpecialCharacters(t *testing.T) {
	overrides := []config.SMBOverride{
		{
			Share: "Media",
			Directives: map[string]string{
				"fruit:time machine": "yes",
				"vfs objects":        "catia fruit streams_xattr",
			},
		},
	}

	result, err := GenerateOverrides(overrides)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	// Special characters should be preserved verbatim
	if !strings.Contains(result, "fruit:time machine = yes") {
		t.Error("fruit:time machine directive not preserved")
	}
	if !strings.Contains(result, "vfs objects = catia fruit streams_xattr") {
		t.Error("vfs objects directive not preserved")
	}
}

func TestGenerateOverrides_ValidSyntax(t *testing.T) {
	overrides := []config.SMBOverride{
		{
			Share: "Media",
			Directives: map[string]string{
				"write list": "media,admin",
				"guest ok":   "no",
			},
		},
	}

	result, err := GenerateOverrides(overrides)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	lines := strings.Split(result, "\n")

	// Verify header is first non-empty line
	headerFound := false
	for _, line := range lines {
		if strings.TrimSpace(line) != "" {
			if strings.HasPrefix(line, "# Generated by unas-custom") {
				headerFound = true
			}
			break
		}
	}
	if !headerFound {
		t.Error("header comment should be first non-empty line")
	}

	// Verify share section format
	if !strings.Contains(result, "[Media]") {
		t.Error("share section should be [ShareName]")
	}

	// Verify directive format (2-space indent, spaces around =)
	if !strings.Contains(result, "  write list = media,admin") {
		t.Error("directives should have 2-space indent and spaces around =")
	}
}

func TestValidateDirectives_EmptyShareName(t *testing.T) {
	overrides := []config.SMBOverride{
		{
			Share: "",
			Directives: map[string]string{
				"write list": "media,admin",
			},
		},
	}

	_, err := GenerateOverrides(overrides)
	if err == nil {
		t.Error("expected error for empty share name")
	}
}

func TestValidateDirectives_EmptyDirectiveKey(t *testing.T) {
	overrides := []config.SMBOverride{
		{
			Share: "Media",
			Directives: map[string]string{
				"": "value",
			},
		},
	}

	_, err := GenerateOverrides(overrides)
	if err == nil {
		t.Error("expected error for empty directive key")
	}
}
